# Generated by Django 3.2.15 on 2022-09-20 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220912_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(verbose_name='Время приготовления'),
        ),
        migrations.AddConstraint(
            model_name='ingredientquantity',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='excluding_duplicate_ingredients'),
        ),
        migrations.AddConstraint(
            model_name='ingredientquantity',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='amount_of_ingredient_must_be_positive_number'),
        ),
    ]
